/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TarsReports } from "./TarsReports";
export * as factories from "./factories";
export { TarsReports__factory } from "./factories/TarsReports__factory";
