/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TarsReportsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getReport"
      | "getReportByCid"
      | "getReportCount"
      | "reports"
      | "submitReport"
      | "updateStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ReportStatusUpdated" | "ReportSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getReport",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReportByCid",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getReportCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reports",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReport",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStatus",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getReport", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReportByCid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReportCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reports", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStatus",
    data: BytesLike
  ): Result;
}

export namespace ReportStatusUpdatedEvent {
  export type InputTuple = [
    index: BigNumberish,
    cid: string,
    status: BigNumberish
  ];
  export type OutputTuple = [index: bigint, cid: string, status: bigint];
  export interface OutputObject {
    index: bigint;
    cid: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReportSubmittedEvent {
  export type InputTuple = [
    index: BigNumberish,
    reporter: AddressLike,
    cid: string,
    timestamp: BigNumberish,
    status: BigNumberish
  ];
  export type OutputTuple = [
    index: bigint,
    reporter: string,
    cid: string,
    timestamp: bigint,
    status: bigint
  ];
  export interface OutputObject {
    index: bigint;
    reporter: string;
    cid: string;
    timestamp: bigint;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TarsReports extends BaseContract {
  connect(runner?: ContractRunner | null): TarsReports;
  waitForDeployment(): Promise<this>;

  interface: TarsReportsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getReport: TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        reporter: string;
        cid: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getReportByCid: TypedContractMethod<
    [cid: string],
    [
      [string, string, bigint, bigint] & {
        reporter: string;
        _cid: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getReportCount: TypedContractMethod<[], [bigint], "view">;

  reports: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        reporter: string;
        cid: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  submitReport: TypedContractMethod<
    [cid: string, timestamp: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  updateStatus: TypedContractMethod<
    [cid: string, newStatus: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getReport"
  ): TypedContractMethod<
    [index: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        reporter: string;
        cid: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReportByCid"
  ): TypedContractMethod<
    [cid: string],
    [
      [string, string, bigint, bigint] & {
        reporter: string;
        _cid: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReportCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reports"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        reporter: string;
        cid: string;
        timestamp: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitReport"
  ): TypedContractMethod<
    [cid: string, timestamp: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateStatus"
  ): TypedContractMethod<
    [cid: string, newStatus: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ReportStatusUpdated"
  ): TypedContractEvent<
    ReportStatusUpdatedEvent.InputTuple,
    ReportStatusUpdatedEvent.OutputTuple,
    ReportStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReportSubmitted"
  ): TypedContractEvent<
    ReportSubmittedEvent.InputTuple,
    ReportSubmittedEvent.OutputTuple,
    ReportSubmittedEvent.OutputObject
  >;

  filters: {
    "ReportStatusUpdated(uint256,string,uint8)": TypedContractEvent<
      ReportStatusUpdatedEvent.InputTuple,
      ReportStatusUpdatedEvent.OutputTuple,
      ReportStatusUpdatedEvent.OutputObject
    >;
    ReportStatusUpdated: TypedContractEvent<
      ReportStatusUpdatedEvent.InputTuple,
      ReportStatusUpdatedEvent.OutputTuple,
      ReportStatusUpdatedEvent.OutputObject
    >;

    "ReportSubmitted(uint256,address,string,uint256,uint8)": TypedContractEvent<
      ReportSubmittedEvent.InputTuple,
      ReportSubmittedEvent.OutputTuple,
      ReportSubmittedEvent.OutputObject
    >;
    ReportSubmitted: TypedContractEvent<
      ReportSubmittedEvent.InputTuple,
      ReportSubmittedEvent.OutputTuple,
      ReportSubmittedEvent.OutputObject
    >;
  };
}
